name: docs

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn

            - name: Build libraries
              run: yarn build:libraries

            - name: Generate doc website
              run: yarn docs

            - name: Publish on Github Pages
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: docs
                  jekyll: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
