name: docs

on:
    push:
        branches:
            - main

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn

            - name: Build libraries
              run: yarn build:libraries

            - name: Generate doc website
              run: yarn docs

            - name: Download artifacts
              run: bash <(curl -sSL "https://raw.githubusercontent.com/privacy-scaling-explorations/snark-artifacts/main/dowload-artifacts")

            - name: Move artifacts to build directory
              run: mkdir -p docs/assets/artifacts && mv *.{wasm,zkey} docs/assets/artifacts

            - name: Publish on Github Pages
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: docs
                  jekyll: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
