name: docs

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v44
              with:
                  files: |
                      packages/**/src/*.{ts,js}

            - if: steps.changed-files.outputs.any_changed == 'true'
              name: Build libraries
              run: yarn build

            - if: steps.changed-files.outputs.any_changed == 'true'
              name: Generate doc website
              run: yarn docs

            - if: steps.changed-files.outputs.any_changed == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
              name: Publish on Github Pages
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: docs
                  jekyll: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
