name: production

on:
    push:
        branches:
            - main

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build | Lint | Format
              run: yarn style
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                type:
                    - contracts
                    - libraries

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build libraries and contracts
              run: yarn build

            - name: Test ${{ matrix.type }}
              run: yarn test:${{ matrix.type }}

            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: run-${{ matrix.type }}
                  path-to-lcov: ./coverage/${{ matrix.type }}/lcov.info
                  parallel: true

    coverage:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
