name: production

on:
    push:
        branches:
            - chore/turbo-prod-action

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build | Lint | Format
              run: yarn style
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                type:
                    - circuits
                    - contracts
                    - libraries

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            # https://github.com/iden3/circuits/blob/8fffb6609ecad0b7bcda19bb908bdb544bdb3cf7/.github/workflows/main.yml#L18-L22
            - name: Setup Circom deps
              run: sudo apt-get update && sudo apt-get install -y wget nlohmann-json3-dev libgmp-dev nasm g++ build-essential

            - name: Setup Circom
              run: wget https://github.com/iden3/circom/releases/latest/download/circom-linux-amd64 && sudo mv ./circom-linux-amd64 /usr/bin/circom && sudo chmod +x /usr/bin/circom

            - name: Install Nargo
              uses: noir-lang/noirup@v0.1.3

            - name: Install dependencies
              run: yarn

              # test turbo task(s) dependsOn build tasks, no need to explicitly build before testing
            - name: Test libraries, contracts and circuits
              run: yarn test

            - name: Coveralls
              if: matrix.type != 'circuits'
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: run-${{ matrix.type }}
                  path-to-lcov: ./coverage/${{ matrix.type }}/lcov.info
                  parallel: true

    coverage:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
