name: pull-requests

on:
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    style:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build | Lint | Format
              run: yarn style

    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                type:
                    - contracts
                    - libraries

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: yarn

            - name: Install dependencies
              run: yarn

            - name: Build libraries and contracts
              run: yarn build

            - name: Test ${{ matrix.type }}
              run: yarn test:${{ matrix.type }}
